# Site settings
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.kanzan.io	" # the base hostname & protocol for your site
permalink: /:title

# Build settings
source: src
destination: www
markdown: kramdown
sass: 
  style: :compressed

